CREATE TABLE users 
(
    id VARCHAR(32) NOT NULL,
    display_name VARCHAR(64) NOT NULL,
    password VARCHAR(128) NOT NULL,
    token VARCHAR(128) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
);